chore: editing apollo client config #132
Amplicode/amplicode-frontend pull request #150
Opened 2022-02-02 07:32 UTC by ilya-trifonov

affects: @amplicode/codegen

2022-02-02 10:39 UTC, vyacheslav-pushkin requested changes

2022-02-02 10:39 UTC, vyacheslav-pushkin commented on example-app/src/app/App.test.tsx
Requirement from the ticket:

> This field should be sorted out and not shown on screens.

2022-02-09 10:25 UTC, vyacheslav-pushkin requested changes

2022-02-09 10:25 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerList.tsx
> +      .filter(p => p !== "id" && p !== "__typename" && entity[p] != null)
We should extract it into a separate function.

2022-02-09 10:25 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerList.tsx
>        .map(p => (
Looks like it will still be shown in editor.

2022-02-10 15:59 UTC, ilya-trifonov commented on example-app/src/app/screens/owner/OwnerList.tsx
> +      .filter(p => p !== "id" && p !== "__typename" && entity[p] != null)
@vyacheslav-pushkin  Should I do it like this?
.filter(p => p !== "id" && entity[p] != null)
.filter(p => p !== "__typename")

2022-02-11 11:09 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerList.tsx
> +      .filter(p => p !== "id" && p !== "__typename" && entity[p] != null)
```
.filter(getDisplayedAttributes)

// Outside the component
function getDisplayedAttributes(attribute: string) {
  return attribute !== "id" && etc.
}
```

2022-02-15 09:29 UTC, vyacheslav-pushkin approved these changes

2022-02-15 09:29 UTC, vyacheslav-pushkin commented
@ilya-trifonov Please resolve conflicts and merge

2022-02-17 07:00 UTC, merged