Lp/feat/139/filters for browser template
Amplicode/amplicode-frontend pull request #185
Opened 2022-02-16 09:03 UTC by HegelPro

2022-02-18 13:37 UTC, vyacheslav-pushkin requested changes

2022-02-18 13:37 UTC, vyacheslav-pushkin commented on packages/react-antd/package.json
> +    "antd": "^4.18.7",
Is there a reason for increasing the minimum version? We have `^4.16.12`in generated app.

2022-02-18 13:37 UTC, vyacheslav-pushkin commented on packages/react-antd/src/components/filters/Filters.tsx
> +export function FilterString<T = any>({caption, attributePath}: FilterStringProps<T>){
We should move them to generated app (`core/crud/filters` folder).

2022-02-18 13:37 UTC, vyacheslav-pushkin commented on packages/react-antd/src/components/filters/Filters.tsx
> +const filterFloatOperators = ["==", "<>", ">", ">=", "<", "<="];
Let's wait for backend before implementing operators.

2022-02-18 13:37 UTC, vyacheslav-pushkin commented on packages/react-core/src/util/path.ts
> +export type AmplicodePath<O extends any, P extends string | L.List> =
I think it should be renamed. `EntityAttribute`?

2022-02-18 15:05 UTC, vyacheslav-pushkin requested changes

2022-02-18 15:05 UTC, vyacheslav-pushkin commented on example-app/package.json
>    "version": "0.1.0",
Tried to check how filter components look, but cannot build `react-antd`:

```
src/index.ts → dist/index.esm.js, dist/index.js...
(node:31513) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/v/work/projects/amplicode/amplicode-frontend/packages/react-antd/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
[!] (plugin rpt2) Error: /home/v/work/projects/amplicode/amplicode-frontend/packages/react-antd/src/components/filters/Filters.tsx(34,9): semantic error TS2322: Type '{ precision: number; style: { width: string; }; addonBefore: Element; }' is not assignable to type 'IntrinsicAttributes & InputNumberProps<ValueType> & { children?: ReactNode; } & { ref?: Ref<HTMLInputElement> | undefined; }'.
  Property 'addonBefore' does not exist on type 'IntrinsicAttributes & InputNumberProps<ValueType> & { children?: ReactNode; } & { ref?: Ref<HTMLInputElement> | undefined; }'.
src/components/filters/Filters.tsx
Error: /home/v/work/projects/amplicode/amplicode-frontend/packages/react-antd/src/components/filters/Filters.tsx(34,9): semantic error TS2322: Type '{ precision: number; style: { width: string; }; addonBefore: Element; }' is not assignable to type 'IntrinsicAttributes & InputNumberProps<ValueType> & { children?: ReactNode; } & { ref?: Ref<HTMLInputElement> | undefined; }'.
  Property 'addonBefore' does not exist on type 'IntrinsicAttributes & InputNumberProps<ValueType> & { children?: ReactNode; } & { ref?: Ref<HTMLInputElement> | undefined; }'.

```

2022-02-18 15:55 UTC, HegelPro commented on example-app/package.json
>    "version": "0.1.0",
`addonBefore` prop was added for `InputNumber` in the `antd 4.17.0`

2022-02-21 11:04 UTC, HegelPro commented on example-app/src/app/menu/Menu.tsx
> +      </Menu.Item>
I didn't find code for adding a nested menu item in AF

2022-02-21 11:08 UTC, HegelPro commented on example-app/src/app/menu/Menu.tsx
> +      </Menu.Item>
I would support the nested menu items in a separate ticket

2022-02-25 11:24 UTC, HegelPro commented on example-app/src/app/screens/demo-components/DemoComponents.tsx
> +export const DemoComponents = () => {
Exist `mobx-react` observer components. For them are better to use the constant syntax:
```typescript
const SomeComponent= observer((props) => {})
```

2022-02-28 15:54 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/demo-components/DemoComponents.tsx
> +export const DemoComponents = () => {
Good point.
In that case let's not enforce either for now.

2022-03-01 12:15 UTC, vyacheslav-pushkin commented
@HegelPro please resolve conflicts

2022-03-05 12:26 UTC, vyacheslav-pushkin requested changes

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerList.tsx
> +export type ItemType = Exclude<ItemListType, null | undefined>[0];
We should avoid numerous files exporting the type with same name.

In fact, `ItemType` was never meant to be exported, it's just a helper type to be used inside the screen. If we wan't a reusable type on application level, we should probably (somehow) use the exact type generated from graphql schema (`OwnerDto` in this case). 

It seems `ItemType` is exported because it is used in filters. **I see no reason to put filters into separate file: it is an integral part of `OwnerList` and is not reused anywhere.**

I suggest to put the filters inside List component file and avoid exporting this type.

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on example-app/src/core/crud/filters/Filters.tsx
> +import { Input, Select, Form, InputNumber, DatePicker, Checkbox } from "antd";
Please put each component into separate file.

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/template-model.ts
> +  if (schema != null && listQueryType != null && filterByAttributes != null) {
Better throw error if `schema` or `listQueryType` is null.

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/template-model.ts
> +  if (schema != null && listQueryType != null && filterByAttributes != null) {
How can `filterByAttributes` be null? Shouldn't it be a compile-time error?

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/template-model.ts
> +      caption: capitalizeFirst(splitByCapitalLetter(attributeName[attributeName.length - 1])),
`developer.lastName` - becomes `Last Name`.
`productOwner.lastName` - becomes `Last Name`.

It think it's not right.

Maybe we should split by capital the whole path. E.g. `Product Owner First Name`. `Technical Certificate Number`.

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/pet/PetList.tsx
> +import { PetListFilters } from "./PetListFilters";
Filter doesn't apply when I click apply:

![image](https://user-images.githubusercontent.com/8298981/156882640-84fbf23a-7b7c-4f57-9cad-c39cc353695c.png)

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/pet/PetList.tsx
> +        <PetListFilters
Filters are not responsive:

![image](https://user-images.githubusercontent.com/8298981/156882715-90b4ace5-38d0-4ac9-87bc-8582b236f3de.png)

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-management/answers.ts
> +    caption: "Select attribute to filter by",
```suggestion
    caption: "Select attributes to filter by",
```

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-management/answers.ts
> +      order: "3",
No, that's very confusing. Filters question should be asked on List step (or if there is no way of doing that - immediately after that step).

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on packages/react-core/src/util/path.ts
> +    : never;
This isn't used anywhere and should be removed.

2022-03-05 12:26 UTC, vyacheslav-pushkin commented on packages/react-core/src/util/path.ts
> +export type EntityAttributeName<T, NotNullT = Exclude<T, null>> = keyof NotNullT | O.Paths<NotNullT>
tsdoc explaining what this type is for will be helpful.

2022-03-05 12:30 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/template-model.ts
> +      caption: capitalizeFirst(splitByCapitalLetter(attributeName[attributeName.length - 1])),
In the demo we have `First Name` and `Last Name` - looks like it refers to Pet. Should be `Owner First Name`, `Owner Last Name`.

2022-03-05 13:00 UTC, HegelPro commented on example-app/src/app/screens/pet/PetList.tsx
> +import { PetListFilters } from "./PetListFilters";
We don't have GraphQL support for filters yet.
We need to know about how it will look like in a GraphQL schema.
And server need to support filters too.

Now apply, it's just console.log

2022-03-05 13:00 UTC, HegelPro commented on packages/codegen/src/generators/react-typescript/entity-list/template-model.ts
> +  if (schema != null && listQueryType != null && filterByAttributes != null) {
`filterByAttributes` if we run generating with command line.
Now `defaultValue` don't set automatically.
Maybe studio set `defaultValue` in automatically then we can remove null checking.

2022-03-05 13:26 UTC, vyacheslav-pushkin requested changes

2022-03-05 13:26 UTC, vyacheslav-pushkin commented on packages/codegen/src/building-blocks/stages/template-model/pieces/amplicode/amplicode.ts
> +export function getGraphQLStringTypeByPath<TSource, TContext>(
Move it into a separate file: `stages/template-model/pieces/graphql-utils/getGraphQLStringTypeByPath.ts`

2022-03-23 10:58 UTC, vyacheslav-pushkin requested changes

2022-03-23 10:58 UTC, vyacheslav-pushkin commented on example-app/package.json
>    "version": "0.1.0",
My comment about antd version is still not addressed.

> Then required `antd` version has to be bumped. It won't work anymore with ` "antd": "^4.16.12"`.

2022-03-23 11:25 UTC, HegelPro commented on example-app/package.json
>    "version": "0.1.0",
It's because we don't `addonBefore` prop for the `InputNumber` in the filters

2022-03-23 11:27 UTC, HegelPro commented on example-app/package.json
>    "version": "0.1.0",
Because of that I lost `antd` version without changing

2022-03-23 13:04 UTC, vadimbasko commented on packages/codegen/src/generators/react-typescript/common/template/Filter.ejs
> +    <InputNumber precision={0} style={{ width: "100%" }} />
I think we shouldn't use inline styles.

2022-03-23 13:40 UTC, vadimbasko commented on packages/codegen/src/building-blocks/stages/template-model/pieces/graphql-utils/getGraphQLStringTypeByPath.ts
> + export function getGraphQLStringTypeByPath<TSource, TContext>(
I think we need test for this.

2022-03-23 15:20 UTC, HegelPro commented on packages/codegen/src/generators/react-typescript/common/template/Filter.ejs
> +    <InputNumber precision={0} style={{ width: "100%" }} />
For Input and DatePicker styles are unnecessarily, I going to delete it. But for InputNumber we need to add styles for width, because it looks more consistently. I think that short InputNumber looks bad:
![886109b94717a38726d433c2bb189c7d](https://user-images.githubusercontent.com/34520941/159731379-2898e6d3-6386-4d90-99cb-3c3554fa03f5.png)

In antd documentation using inline styles for setting width: [example](https://ant.design/components/form/#components-form-demo-register)

2022-03-28 12:04 UTC, vyacheslav-pushkin requested changes
Why is there a change in react-core package-lock?

2022-03-30 09:30 UTC, HegelPro commented
> Why is there a change in react-core package-lock?

It was unnecessarily. Remaining after running `lerna bootstrap`.
Now it's removed.

2022-03-31 09:23 UTC, vyacheslav-pushkin approved these changes

2022-03-31 09:25 UTC, vyacheslav-pushkin commented
@HegelPro Please resolve conflicts, merge, and move ticket to QA

2022-03-31 12:52 UTC, merged