feat: ensuring GraphQL operation name uniqueness #152
Amplicode/amplicode-frontend pull request #191
Opened 2022-02-22 07:06 UTC by ilya-trifonov

affects: @amplicode/codegen

2022-03-02 13:48 UTC, vyacheslav-pushkin requested changes

2022-03-02 13:48 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-details/template-model.ts
> +    : undefined;
Do we really need all this? Why don't we just concat existing query name with component name?

2022-03-02 13:48 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/template-model.ts
> +    : undefined
Same here

2022-03-04 07:47 UTC, ilya-trifonov commented on packages/codegen/src/generators/react-typescript/entity-details/template-model.ts
> +    : undefined;
i did it because our queryName is query operation name, but we need to change query name in queryString.
so I add query name as queryTitle and used it to replase name and create new query string.
same for mutations.

2022-03-09 17:19 UTC, ilya-trifonov commented on packages/codegen/src/generators/react-typescript/entity-details/template-model.ts
> +    : undefined;
I added these steps because we have different name and operation name. And I need to find the correct name to replace it in the right way for query and mutation

2022-03-11 16:06 UTC, vyacheslav-pushkin commented
It was decided to implement it on Studio side (see AST-114).

2022-03-11 16:06 UTC, closed without merging