feat: add route as a separate screen template parameter #178
Amplicode/amplicode-frontend pull request #201
Opened 2022-02-28 13:54 UTC by ilya-trifonov

affects: @amplicode/codegen

2022-03-01 12:14 UTC, vyacheslav-pushkin commented
@ilya-trifonov please resolve conflicts

2022-03-02 13:43 UTC, vyacheslav-pushkin requested changes

2022-03-02 13:43 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-management/answers.ts
> +  },
It should have `relatedProperty` pointing to component name.

2022-03-02 13:43 UTC, vyacheslav-pushkin commented on packages/codegen/src/building-blocks/stages/answers/amplicode/ScreenAnswers.ts
> +  route?: string,
It should be mandatory. Studio will provide the default.

2022-03-02 13:43 UTC, vyacheslav-pushkin commented on packages/codegen/src/building-blocks/stages/answers/pieces/defaultAnswers.ts
> +});
Why do we need all this?

2022-03-02 13:43 UTC, vyacheslav-pushkin commented on packages/codegen/src/building-blocks/stages/writing/pieces/mvp/addMvpAppMenu.ts
> +  if (route != null) {
`route` should be mandatory

2022-03-02 13:43 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/answers.ts
> +  },
`relatedProperty` should point to component name

2022-03-02 13:43 UTC, vyacheslav-pushkin commented on scripts/generate-owner-management.js
> +// const {toKebabCase} = require('./../packages/codegen/src/building-blocks/util')
Please remove this line

2022-03-04 07:01 UTC, ilya-trifonov commented on packages/codegen/src/building-blocks/stages/answers/amplicode/ScreenAnswers.ts
> +  route?: string,
route is needed in the list components only, that's why I did it..

2022-03-04 12:39 UTC, vyacheslav-pushkin approved these changes

2022-03-04 12:39 UTC, merged