Lp/refactor/127/message store provider api
Amplicode/amplicode-frontend pull request #206
Opened 2022-03-03 09:45 UTC by HegelPro

2022-03-04 13:33 UTC, vyacheslav-pushkin requested changes

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on example-app/src/index.tsx
> +        messages: messageStore.messagesMapping["en"]
I think we need to rename `MessageStore` into `I18nStore` because I think it's the right place to store the currently selected locale.

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/DynamicI18nMessagesProvider.tsx
> +import { useEffect } from "react"
This should not be in `react-core` (it's part of an existing addon).

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/IntlMessagesProvider.tsx
> +import { observer } from "mobx-react";
I think it should be in the generated app under `core/i18n/providers`

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/MessageStore.tsx
> +export type MessagesMapping = Record<string, Record<string, string>>;
Please replace it with a single data structure. It should be an object, not an array, so we don't have to traverse it each time. Something like:

```
export type I18nConfig {
  [localeCode: string]: {
    localeCaption: string;
    direction: 'rtl' | 'ltr';
    messages: {
      [messageKey: string]: string
    }
  }
}
```

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/MessageStore.tsx
> +  }
Why do we need this method?

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/MessageStore.tsx
> +      console.error(`${locale} locale is undefined you can't add messages to this locale`);
I don't think we should log an error in this case. E.g. an addon can provide i18n for 100 locales, but only 2 are used in the project - we don't want 98 errors in console.

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/MessageStore.tsx
> +    this.currentLocale = locale;
What if we attempt to set a locale that is not in the available locales?

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/MessageStore.tsx
> +  }
I don't think we need this method if we have `currentMessages` and `getMessages`.

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/StaticI18nMessagesProvider.tsx
> +  }, [messageStore, messageStore.localesInfo, messagesMapping]);
`messageStore.localesInfo` doesn't seem to be used in the hook

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/MessageStore.tsx
> +  }
We should probably remove these methods

2022-03-04 13:33 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/MessageStoreContext.tsx
> +  localeConfigs: LocaleConfig[];
I think we should not provide both. We should either provide `localeConfigs` and create `messageStore` inside the provider (but then we need to rewrite the way intl is used in axios interceptors - probably instead of directly invoking notification we should emit an event that will be somehow dealt with from inside React context). Or we should create `messageStore` from `localeConfigs` before passing it into `I18nProvider` (then no much sense in `MessageStoreProvider`).

I'm inclined towards first option.

2022-03-04 14:39 UTC, HegelPro commented on example-app/src/index.tsx
> +        messages: messageStore.messagesMapping["en"]
I agree, that this name is better, because locale word more important in this store. Messages are part of locale.

2022-03-04 14:39 UTC, HegelPro commented on example-app/src/core/i18n/providers/AnyAddonProvider.tsx
> +import { useMessageStore } from "@amplicode/react-core"
Yes, it's a part of an addon

2022-03-04 15:08 UTC, HegelPro commented on packages/react-core/src/i18n/MessageStore.tsx
> +    this.currentLocale = locale;
We will see code messages. If `currentLocale` is not avaible `currentMessages` will be undefined. `messages` prop in IntlProvider could be undefined.

2022-03-04 15:09 UTC, HegelPro commented on packages/react-core/src/i18n/MessageStore.tsx
> +  }
Now we don't use it. I saved it from the previous version of localesStore.

2022-03-14 15:32 UTC, vyacheslav-pushkin requested changes

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/I18nProvider.tsx
> +import { I18nStore, I18nStoreContext } from "@amplicode/react-core";
No ticket number in commit message

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/I18nProvider.tsx
> +        <IntlMessagesProvider>{children}</IntlMessagesProvider>
I think better name is `I18nApiProvider`. Because it doesn't provide *messages* (like `StaticI18nMessagesProvider` does), it provides *API* (`intl`).

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on example-app/src/index.tsx
> +      <I18nProvider i18nStore={i18nStore} staticMessages={staticMessages}>
Let's hide `i18nStore` inside `I18nStoreProvider` and `staticMessages` inside `StaticI18nMessagesProvider`.

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/I18nProvider.tsx
> +  staticMessages: Record<string, Record<string, string>>;
Let's remove these props and create these values inside corresponding providers.

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/StaticI18nMessagesProvider.tsx
> +  staticMessages: Record<string, Record<string, string>>;
Let's remove this prop and create `staticMessages` right here.

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on example-app/src/i18nConfig.ts
> +};
This should live in `I18nStoreProvider`.

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/I18nStore.tsx
> +  localeConfigs: Record<string, LocaleConfig> = {};
I think that

```
{ [locale: string]: LocaleConfig }
```

is better than `Record<string, LocaleConfig>` because it is self-documenting.

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/I18nStore.tsx
> +    this.currentLocale = locale;
See above comment about non-existent locale.

2022-03-14 15:32 UTC, vyacheslav-pushkin commented on packages/react-core/src/i18n/I18nStore.tsx
> +  }
See above comment about avoiding tight coupling with `intl`.

2022-03-14 15:33 UTC, vyacheslav-pushkin commented
Also please fix conflicts

2022-03-17 09:50 UTC, HegelPro commented on example-app/src/i18nConfig.ts
> +};
I thought that better to force users don't to write code in the `core` folder. And configs better to keep in the root like a part of code where you can do anything.

2022-03-18 20:09 UTC, HegelPro commented on example-app/src/index.tsx
> +        message: i18nStore.intl.formatMessage({ id: "common.notAllowed" })
I tried to use eventEmitter. Please check it out.
Do I understand correctly how it should look like?

2022-03-22 14:19 UTC, vyacheslav-pushkin approved these changes
Just a couple of minor comments, please fix them and merge

2022-03-22 14:19 UTC, vyacheslav-pushkin commented on example-app/src/index.tsx
> +  amplicodeEmitter.emit("axiosGetResponse", response);
Let's rename the event to `unauthorized` and emit it only when `response.status === 401`.

2022-03-22 14:19 UTC, vyacheslav-pushkin commented on example-app/src/core/amplicode/AmplicodeEmitter.ts
> +  axiosGetResponse: (response: AxiosResponse) => void;
I think it's clearer to export this type:

```
export type ServerErrorEvents = {
  graphQLError: ErrorHandler;
  axiosGetResponse: (response: AxiosResponse) => void;
}
```

and replace `AmplicodeEventEmitter` in other places with `EventEmitter<ServerErrorEvents>`

2022-03-22 14:19 UTC, vyacheslav-pushkin commented on example-app/src/index.tsx
> +export const amplicodeEmitter: AmplicodeEventEmitter = new EventEmitter();
```suggestion
export const serverErrorEmitter = new EventEmitter<ServerErrorEvents>();
```

2022-03-23 09:57 UTC, merged