chore: remove /* GraphQL */ from screen templates #165
Amplicode/amplicode-frontend pull request #222
Opened 2022-03-14 07:40 UTC by ilya-trifonov

affects: @amplicode/codegen

2022-03-16 08:08 UTC, ilya-trifonov commented on example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx
> +
@vyacheslav-pushkin 
empty lines are added after the screens are generated. Syntax highlighting in these queries also disappeared. Everything works fine if we don`t remove /* GraphQL */

2022-03-16 09:09 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx
> +
Where the empty lines are coming from?

2022-03-16 09:11 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx
> +
Which version of Studio are you using?

2022-03-16 09:36 UTC, ilya-trifonov commented on example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx
> +
I use npm run-bootstrap-react-app to generate screens.

2022-03-17 09:09 UTC, vyacheslav-pushkin requested changes

2022-03-17 09:09 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerCards.tsx
> +      }
Extra whitespace appeared

2022-03-21 12:46 UTC, vyacheslav-pushkin approved these changes

2022-03-21 12:46 UTC, vyacheslav-pushkin commented
@ilya-trifonov please resolve conflicts and merge

2022-03-21 14:49 UTC, merged