Lp/feat/245/support dayjs localisation
Amplicode/amplicode-frontend pull request #284
Opened 2022-04-04 11:43 UTC by HegelPro

2022-04-04 11:46 UTC, HegelPro commented
Depends on [#246](https://github.com/Amplicode/amplicode-frontend/pull/276)

2022-04-04 13:27 UTC, vyacheslav-pushkin requested changes

2022-04-04 13:27 UTC, vyacheslav-pushkin commented on example-app/package-lock.json
>          "@types/react-router-dom": "^5.1.9",
Please remove all antd-localization-related code from this ticket and leave only the code related to localization of dayjs.

2022-04-04 13:27 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/I18nProvider.tsx
> +import "dayjs/locale/ru";
Can we import it dynamically?

It think `LocaleConfig` can contain this path (along with caption and antd locale).

2022-04-04 13:27 UTC, vyacheslav-pushkin commented on example-app/src/antd/DatePicker.tsx
> +export const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig);
I think `DatePicker` and `TimePicker` are very unlikely to be customized, and therefore can be safely moved to the lib. It will also simplify importing it from different places of the app.

2022-04-04 13:27 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/app/template-model.ts
> +]
Let's not add it for now. Let's hardcode `en` and `ru` in the `app` template. In a separate ticket we will add a Studio parameter to define available locales.

2022-04-05 12:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Amplicode/amplicode-frontend?pullRequest=284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Amplicode/amplicode-frontend?pullRequest=284) before we can accept your contribution.<br/><hr/>**HegelPro** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Amplicode/amplicode-frontend?pullRequest=284) it.</sub>

2022-04-06 12:40 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/DayjsProvider.tsx
> +      `../../../../node_modules/dayjs/esm/locale/${currentLocale}.js`
```suggestion
      `dayjs/esm/locale/${currentLocale}`
```

I think it should work like this.

2022-04-06 12:43 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/DayjsProvider.tsx
> +    import(
I suggest giving a human-readable name to the generated chunk by using [webpackChunkName](https://webpack.js.org/api/module-methods/#magic-comments) comment.

2022-04-06 13:00 UTC, HegelPro commented on example-app/src/core/i18n/providers/DayjsProvider.tsx
> +      `../../../../node_modules/dayjs/esm/locale/${currentLocale}.js`
It won't work. Vite has rules for using dynamic imports:
https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations

2022-04-06 14:35 UTC, merged