feat: support graphQL query for templates with filters
Amplicode/amplicode-frontend pull request #292
Opened 2022-04-07 08:21 UTC by HegelPro

affects: @amplicode/codegen

2022-04-08 12:25 UTC, vyacheslav-pushkin requested changes

2022-04-08 12:25 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerTableWithFilter.tsx
> +        </Button>
I think it better to rename "Clear" -> "Reset".
The button should not only clear the fields, but also reset the items selection (i.e apply).

2022-04-08 12:25 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerTableWithFilter.tsx
> +            <Input />
Let's add "clear" icon that will clear the given input (but will not apply the filters). The icon should be the same to one used in EntityLookupField.

2022-04-08 13:22 UTC, HegelPro commented on example-app/src/app/screens/owner/OwnerTableWithFilter.tsx
> +import { useEffect, useState } from "react";
We need to support petList query with filter in [amplicode-mvp-petclinic](https://github.com/Amplicode/amplicode-mvp-petclinic). Now is supported query with filter just for Owner entity.
I can add filter logic to petList but filters will not applying until backend supporting in [amplicode-mvp-petclinic](https://github.com/Amplicode/amplicode-mvp-petclinic) project.

2022-04-22 09:53 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerTableWithFilter.tsx
> +        </Button>
> The button should not only clear the fields, but also reset the items selection (i.e apply).

This is not done.

2022-04-22 09:55 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/owner/OwnerTableWithFilter.tsx
> +import { useEffect, useState } from "react";
We need entity-management examples both with and without filters. Therefore please create the following screens:

- Owner Table (no filters)
- Owner Cards (no filters)
- Owner List (no filters)
- new Owner Cards (with filters)
- Pet Table (with filters)
- Pet Cards (with filters)
- Pet List (with filters)

2022-04-22 10:55 UTC, vyacheslav-pushkin approved these changes
Please fix comments and merge

2022-04-22 10:55 UTC, vyacheslav-pushkin commented on packages/codegen/src/common/studio/studio-model.ts
> +  ARGUMENT = 'ARGUMENT',
Please remove `ARGUMENT`. Every argument we add must be supported by Studio, but this one is not used anywhere yet.

2022-04-22 10:55 UTC, vyacheslav-pushkin commented on packages/codegen/src/common/studio/studio-model.ts
> +  ARGUMENT_ARRAY = 'ARGUMENT_ARRAY',
Let's rename it to `FILTER_QUERY_ARGUMENT_ARRAY`. We will likely want Studio to exclude arguments related to pagination and sorting, so I think we need a less generic / more semantic name.

2022-04-22 10:55 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/answers.ts
>      defaultValue: [],
Please remove `defaultValue`.

2022-04-22 10:55 UTC, vyacheslav-pushkin commented on scripts/generate-management/owner-management-table.js
> +    filterByArguments: [['filter', 'firstName'], ['filter', 'lastName']]
Let's add the tests for the following casses:

- `filterByArguments` is `null`
- `filterByArguments` is `undefined`
- `filterByArguments` is empty array

For all these cases we need to generate a screen without filters.

2022-04-25 08:12 UTC, merged