fix: components using dayjs are not updated when changing locale #322
Amplicode/amplicode-frontend pull request #369
Opened 2022-05-06 10:00 UTC by HegelPro

affects: @amplicode/codegen, @amplicode/react-antd

2022-05-06 12:52 UTC, vyacheslav-pushkin requested changes
Doesn't fix the problem

![image](https://user-images.githubusercontent.com/8298981/167134977-6591a51b-1c34-4cc2-b9ca-6e11ebc535f9.png)

2022-05-06 13:51 UTC, HegelPro commented
> Doesn't fix the problem
> 
> ![image](https://user-images.githubusercontent.com/8298981/167134977-6591a51b-1c34-4cc2-b9ca-6e11ebc535f9.png)

fixed

2022-05-06 14:51 UTC, vyacheslav-pushkin requested changes

2022-05-06 14:51 UTC, vyacheslav-pushkin commented on example-app/src/core/i18n/providers/DayjsProvider.tsx
> +    });
This will unmount the whole subtree and make it lose state. There should be a better solution.

2022-05-13 12:58 UTC, vyacheslav-pushkin approved these changes

2022-05-13 12:59 UTC, vyacheslav-pushkin commented
@HegelPro please resolve conflicts and merge

2022-05-13 13:34 UTC, merged