fix: table looks ugly when too many columns #423
Amplicode/amplicode-frontend pull request #431
Opened 2022-05-30 08:57 UTC by ilya-trifonov

affects: @amplicode/codegen

2022-05-31 11:21 UTC, vyacheslav-pushkin requested changes

2022-05-31 11:21 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/management/TestScalarsTable.tsx
> +        scroll={{ x: 1024 }}
Why use specific value?

2022-05-31 11:52 UTC, ilya-trifonov commented on example-app/src/app/screens/management/TestScalarsTable.tsx
> +        scroll={{ x: 1024 }}
we use a custom max width for the layout. 
`.narrow-layout {
    max-width: 1024px;
    margin: auto;
}`
So I used the same width for the table.
But, it would be better to change it to "100%"

2022-06-01 10:33 UTC, vyacheslav-pushkin requested changes

2022-06-01 10:58 UTC, ilya-trifonov commented on example-app/src/app/screens/management/OwnerTable.tsx
> +        scroll={{ x: "100%" }}
I'll do it

2022-06-02 09:27 UTC, vyacheslav-pushkin approved these changes

2022-06-02 09:27 UTC, merged