feat: add Amplicode logo to the header #409
Amplicode/amplicode-frontend pull request #433
Opened 2022-05-30 13:11 UTC by ilya-trifonov

affects: @amplicode/codegen

2022-05-31 11:11 UTC, vyacheslav-pushkin requested changes

2022-05-31 11:11 UTC, vyacheslav-pushkin commented on example-app/src/app/header/Header.css
> +
What is the reason for adding this?

2022-06-01 11:06 UTC, ilya-trifonov commented on example-app/src/app/header/Header.css
> +
Perhaps these styles will need to be changed in a task with horizontal navigation

2022-06-02 12:33 UTC, vyacheslav-pushkin approved these changes

2022-06-02 12:33 UTC, merged