feat: sorting and pagination #396
Amplicode/amplicode-frontend pull request #493
Opened 2022-07-01 09:58 UTC by HegelPro

affects: @amplicode/codegen

2022-07-01 16:37 UTC, vyacheslav-pushkin requested changes

2022-07-01 16:37 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/management/OwnerCardsWithFilterSortPage.tsx
> +        )
Looks like we repeat this code twice.

2022-07-04 12:58 UTC, vyacheslav-pushkin requested changes

2022-07-04 12:58 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/common/template/OrderByButtonWrapperEnd.ejs
> +        style={{ minWidth: "220px" }}
Better to extract it into CSS class

2022-07-04 12:58 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/management/OwnerTableWithFilterSortPage.tsx
> +  };
Let's wrap it in `useCallback` so that `Pagination` component is not recreated on each render.

2022-07-04 12:58 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/management/OwnerTableWithFilterSortPage.tsx
> +  };
Let's wrap in `useCallback`

2022-07-04 12:58 UTC, vyacheslav-pushkin commented on packages/codegen/src/generators/react-typescript/entity-list/answers.ts
> +    caption: "Select an argument to order by",
Can be multiple arguments

2022-07-04 12:58 UTC, vyacheslav-pushkin commented on scripts/bootstrap-app/generate-management/owner-management-list-with-filter-sort-page.js
> +  orderByArguments: [['sort', 'property', 'CITY'], ['sort', 'property', 'FIRST_NAME']],
We don't need `sort` and `property` here since argument structure is will always be the same.
We need to add sort direction.

For example:

```
orderByArguments: [{property: 'CITY', direction: 'ASC'}, {property: 'FIRST_NAME', direction: 'DESC'}]
```

2022-07-04 12:58 UTC, vyacheslav-pushkin commented on scripts/bootstrap-app/generate-management/owner-management-list-with-filter-sort-page.js
> +  paginationArgument: ['page']
I think we need type of pagination here ('none' | 'offset' | 'cursor')

2022-07-07 08:02 UTC, HegelPro commented on scripts/bootstrap-app/generate-management/owner-management-list-with-filter-sort-page.js
> +  paginationArgument: ['page']
I think that we don't need to use the 'none' string when we can pass undefined value instead

2022-07-07 13:53 UTC, HegelPro commented on example-app/src/app/screens/management/OwnerCardsWithFilterSortPage.tsx
> +        <Pagination
Is it ok? Because graphQL data while loading is undefined.
![image](https://user-images.githubusercontent.com/34520941/177788260-fb7f1ffe-04d6-4843-914c-0e42d1b8cc36.png)

2022-07-08 09:42 UTC, vyacheslav-pushkin approved these changes

2022-07-08 09:42 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/management/OwnerListsWithFilterSortPageEditor.tsx
> +import { ErrorMessage } from "../../../core/crud/ErrorMessage";
example-app needs to be re-generated

2022-07-08 09:42 UTC, vyacheslav-pushkin commented on example-app/src/app/screens/management/OwnerCardsWithFilterSortPage.tsx
> +        <Pagination
This will still cause flickering. Please create a separate issue for that. My screenshot above shows how it should look like. This was achieved by just adding `loading` prop to your previous version of the table.

2022-07-08 09:43 UTC, merged