fix: filtering without pagination doesn't work #523
Amplicode/amplicode-frontend pull request #535
Opened 2022-07-19 08:13 UTC by HegelPro

affects: @amplicode/codegen

2022-07-21 11:03 UTC, vadimbasko commented on example-app/src/core/transform/transform.ts
> +  } else {
Please add comment, which type of `data` we expect here. May be we need to add one more else, if data is not of expected type.

2022-07-21 11:06 UTC, vadimbasko requested changes
@HegelPro please add screens as decribed below in example-app.

generator: entity-management
mode: edit
entity: Pet
variants:
1. with filter and pagination
2. with pagination only (no filter)
3. with filter only (no pagnation)

Examples should be added for 'cards' and 'table' collection types.

2022-07-26 06:20 UTC, HegelPro commented
> @HegelPro please add screens as described below in example-app.
> 
> generator: entity-management mode: edit entity: Pet variants:
> 
> 1. with filter and pagination
> 2. with pagination only (no filter)
> 3. with filter only (no pagination)
> 
> Examples should be added for 'cards' and 'table' collection types.

Add those screens for the Owner entity. Pet has no gql queries for generating only sort or only pagination.

2022-07-27 05:48 UTC, vadimbasko approved these changes

2022-07-27 05:49 UTC, merged