feat: add i18n metadata for palette items #492
Amplicode/amplicode-frontend pull request #548
Opened 2022-07-29 12:51 UTC by vadimbasko

affects: @amplicode/codegen

2022-08-15 13:54 UTC, web-devel requested changes
I suggest to remove empty `messageProps`.
Also I thought there will be more localisable props (but it was just an assumption)

2022-08-15 13:54 UTC, web-devel commented on example-app/src/dev/rb-metadata.json
> +      "messageProps": []
Why it's an empty array?

2022-08-15 13:54 UTC, web-devel commented on example-app/src/dev/rb-metadata.json
> +      "messageProps": []
Why it's an empty array?

2022-08-26 12:25 UTC, vyacheslav-pushkin commented on example-app/src/dev/rb-metadata.json
> +      "messageProps": []
Removed empty arrays. Checked several components in the docs - seems that message props are defined correctly.

2022-08-30 07:44 UTC, web-devel approved these changes

2022-08-30 07:48 UTC, merged