Ad/refactor/27/named exports
Amplicode/amplicode-frontend pull request #62
Opened 2021-10-20 16:17 UTC by deanex

2021-10-21 10:05 UTC, vyacheslav-pushkin requested changes

2021-10-21 10:05 UTC, vyacheslav-pushkin commented on packages/codegen/src/building-blocks/stages/writing/pieces/mvp/addMvpAppMenu.ts
> +  screenRegistryTransformed = transformAddScreenImport(screenRegistryTransformed, componentName, componentPath, false);
Why do we need this change? It will likely break the addon generator.

2021-11-08 07:56 UTC, deanex commented on packages/codegen/src/building-blocks/stages/writing/pieces/mvp/addMvpAppMenu.ts
> +  screenRegistryTransformed = transformAddScreenImport(screenRegistryTransformed, componentName, componentPath, false);
It shouldn't break the addon generator because if component is addon then `!isAddon === false`
For both cases: addons and app components, we need to have named imports, so flag `isDefault` set to `false`

2021-11-08 08:23 UTC, vyacheslav-pushkin commented on packages/codegen/src/building-blocks/stages/writing/pieces/mvp/addMvpAppMenu.ts
> +  screenRegistryTransformed = transformAddScreenImport(screenRegistryTransformed, componentName, componentPath, false);
OK, I see now what you did.

I would prefer to change the default of `isDefault` to `false`:

```
export function transformAddScreenImport(
  source: string, 
  componentName: string, 
  componentPath: string, 
  isDefault: boolean = false): string 
{
```

and don't pass `isDefault` when invoking function:

```
screenRegistryTransformed = transformAddScreenImport(screenRegistryTransformed, componentName, componentPath);
```

2021-11-08 11:56 UTC, vyacheslav-pushkin approved these changes

2021-11-08 11:56 UTC, merged