WIP: add example of i18n for graphql DTO
Amplicode/amplicode-frontend pull request #824
Opened 2023-05-24 08:29 UTC by HegelPro

2023-06-06 16:09 UTC, vadimbasko commented on packages/codegen/src/building-blocks/util/parseTs.ts
> +    parser: require("recast/parsers/babel-ts"),
@HegelPro need comment, why we should use recast here. Links to doc also will be nice to have.

2023-06-06 16:16 UTC, vadimbasko commented on packages/codegen/src/building-blocks/stages/template-model/pieces/getEntityMessages.ts
> +export function getEntityMessages(
Please add comment with function description. And unit test `getEntityMessages.test.ts`

2023-06-06 16:29 UTC, vadimbasko commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> +  );
Not sure that we need so many lines for this code, read better in one line
```suggestion
  const localePath = path.join(screenPaths.localeMessagesPath, `${localeName}.ts`);
```

There are also several similar cases in this file.

2023-06-06 16:30 UTC, vadimbasko commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> +    }).length === 0;
```suggestion
  const hasResourcesProperty =
    localeVariable.find(j.ObjectProperty, {key: { name: "resources" }}).length === 0;
```

2023-06-06 16:43 UTC, vadimbasko commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.test.ts
> +  });
If there is no 'en' object in file, error should be thrown
```suggestion
  it("should throw obvious error message if there is no 'en' object in file", function() {
    const locale = `
    export const incorrectLocalObjectName: TranslationMessages = {
      ...englishMessages,
    }`;
    // TODO Error should be thrown, error message should be clear
    mergeI18nMessagesWithLocaleFileContent(locale, "en", {});
  });
```

2023-06-06 16:47 UTC, vadimbasko commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> +  const localeFile = await fs.readFile(localePath, "utf-8");
Add check, that 'localeFile' exist. If no - throw error with comprehensive message.

2023-06-06 16:50 UTC, vadimbasko commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> + * then find "resources" property inside variable
```suggestion
 * then find "resources" property inside variable, if there is no 'resources' property - create it
```

2023-06-06 16:57 UTC, vadimbasko commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> +  screenPaths: ScreenPaths,
we don't need all `screenPaths` here, `localeMessagesPath` is enough

2023-06-06 17:06 UTC, vadimbasko requested changes
A few things should be clarified. Do not merge PR after fix, I will look on it once more after changes will be made.

2023-06-06 21:27 UTC, HegelPro commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> +    }).length === 0;
It's prettier formatter

2023-06-06 21:28 UTC, HegelPro commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> +  );
It's prettier formatter

2023-06-07 02:01 UTC, vadimbasko commented on packages/codegen/src/generators/react-admin/common/mergeI18nMessagesWithLocaleFile.ts
> +  );
Prettier is not standard for code in 'codegen' package. The only place where it must - is generated code. 
Code readability has higher priority than prettier formatting for code in 'codegen'. If you are using prettier formatting, please review your code after it. 
Also I can suggest increase line length in prettier settings (printWidth: 100). This value we are using in generated code formatting  <https://github.com/Amplicode/amplicode-frontend/blob/master/packages/codegen/src/building-blocks/stages/configuring/defaultConfigureGenerator.ts#L62>

2023-06-09 06:30 UTC, vadimbasko approved these changes
A few TODO added, but we will discuss them after merge.

2023-06-09 06:30 UTC, merged